### ISSUE TITLE
scholarly markdown, rmarkdown, latex, citr, 

### ISSUE THREAD

**Issue by RMHogervorst** [RMHogervorst/cleancode#30]
introduction to what all the tools are, as replacement for word reference managers. 

set up: collect and annotate documents in zotero, save to bibtex file.

write in rmarkdown and add citations with button, can search in it 
was already possible to use citations, but is a bit annoying. 
http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html

therefor button is really nice. 

links to other projects: 
https://github.com/scholmd/scholmd

**Comment by mikoontz** [comment]
I really liked the post that came from this idea!

I have one suggestion: it's pretty easy to add different citation styles in RMarkdown using the csl: argument in the YAML. You can use a website and pull them directly from the csl GitHub repository ([https://github.com/citation-style-language/styles](https://github.com/citation-style-language/styles))

Here is my workflow: [https://twitter.com/_mikoontz/status/838859261572591623](https://twitter.com/_mikoontz/status/838859261572591623)

Do you think that's within the scope of your piece?

**Comment by RMHogervorst** [comment]
It is! I'll add it, thanks!
