### ISSUE TITLE
Suggested extra content link for NSE_standard_evaluation_dplyr.html 

### ISSUE THREAD

**Issue by JohnMount** [RMHogervorst/cleancode#48]
Hi Roel,

I like your post on rmhogervorst.nl/cleancode: http://rmhogervorst.nl/cleancode/blog/2016/06/13/NSE_standard_evaluation_dplyr.html .

I have a package replyr up on CRAN that helps with this task and a free video demonstrating how to use the package https://youtu.be/iKLGxzzm9Hk .  I'd love for you to give replyr::let a look and perhaps recommend it.

**Comment by RMHogervorst** [comment]
Hi @JohnMount !
The package looks great! the standard evaluation (and naming of the resulting variables!) is indeed up for an improvement. I don't have a lot of time now, but I will definitely play with your package. And probably add it to the page. Thanks for the heads up!

**Comment by JohnMount** [comment]
Thanks, and no rush!  Just a note I have cleaned up the documentation and move the functionality to a new CRAN package called wrapr.  Much smaller package.  replyr will continue to work by the usual re-import method.

**Comment by RMHogervorst** [comment]
Hi @JohnMount, what are your thoughts about dplyr 0.6? Does it make wrapr::let obsolete or is there still value?

**Comment by JohnMount** [comment]
Actually I have changed my answer: after plying with dplyr 0.6 a bit I still suggest using wrapr::let() http://www.win-vector.com/blog/2017/05/why-to-use-wraprlet/ .  The reasons beeing wrapr::let() accepts variable names from strings more directly and as smaller (safer) interaction surface with magrittr.  Some text on the topic: http://www.win-vector.com/blog/2017/05/why-to-use-wraprlet/

**Comment by RMHogervorst** [comment]
I really like the packages, but others, including you, have said it much better than I could.
