### ISSUE TITLE
Minor typographical error ins 

### ISSUE THREAD

**Issue by rmsharp** [RMHogervorst/cleancode#53]
The following line (appears in the first paragraph after the NSE heading) has the first word misspelled.

_qoutes_ but in some functions you don’t. They are designed to work in a non-standard way. 

Should be

quotes but in some functions you don’t. They are designed to work in a non-standard way.

**Comment by rmsharp** [comment]
Two paragraphs later the "send" appears where "sent" should.

the lazyeval package and is then _send_ to the SE version. There is even a naming scheme 2:

**Comment by RMHogervorst** [comment]
Thanks! I really appreciate you pointing this out to me. I have updated the post, r-bloggers might not pick this up though.
