### ISSUE TITLE
Markov chains!

### ISSUE THREAD

**Issue by juliasilge** [RMHogervorst/cleancode#54]
Hello there, Roel! I love TNG so much, and your post was so fun. Just FYI I have been experimenting with Markov chains with quite a lot of success using this package:
[https://github.com/abresler/markovifyR](https://github.com/abresler/markovifyR)
Text generation is so much fun. 😃

**Comment by RMHogervorst** [comment]
Yes! It is! 
That package is much better at it then what I did, I believe.

**Comment by RMHogervorst** [comment]
Although I don't like the dependency on python.

**Comment by juliasilge** [comment]
It's true, but I have found packages like this that use [reticulate](https://github.com/rstudio/reticulate) to work very smoothly from R.

**Comment by RMHogervorst** [comment]
Yeah I probably have misconfigured some python stuff (anaconda and pip , messing with virtualenv ) you probably know the deal. 

I have recently used your book (and david too of course) on tidy textmining for a non text related thing. I love how the tidy principles can be used everywhere! Very nice work
