### ISSUE TITLE
Winter temp / Humidex swapped for D_CARI table

### ISSUE THREAD

**Issue by jonspring** [RMHogervorst/cleancode#56]
Fun post applying Maele Salmon's analysis to the Netherlands!
http://rmhogervorst.nl/cleancode/blog/2017/11/20/xkcd-the-netherlands-weather.html

I think you accidentally swapped the humidex and winter temps when you defined the D_CARI table:
D_CARI <- tribble(
      ~NAME, ~humidex_avg, ~wintertemp,
      "Bonaire, Caribbean Netherlands", 27, calcHumx(29,76),
      "Sint Eustatius, Caribbean Netherlands", 28, calcHumx(28,77),   
      "Saba, Caribbean Netherlands",30, calcHumx(30,76)
  )

should be:

D_CARI <- tribble(
      ~NAME, ~humidex_avg, ~wintertemp,
      "Bonaire, Caribbean Netherlands",  calcHumx(29,76), **27,**
      "Sint Eustatius, Caribbean Netherlands", calcHumx(28,77),   **28,** 
      "Saba, Caribbean Netherlands", calcHumx(30,76) **30** 
  )

**Comment by RMHogervorst** [comment]
I did! Thanks!
