### ISSUE TITLE
Git <<<<HEAD... in web-scraping post

### ISSUE THREAD

**Issue by batpigandme** [RMHogervorst/cleancode#57]
Hi Roel,
Great issue template! Just wanted to let you know that it looks like a merge conflict header ended up in the rendered version of your lasted post. It's not in the md, but you'll see it if you go to the [page](http://rmhogervorst.nl/cleancode/blog/2017/12/08/downloading-multiple-files-and-failing.html). Good stuff, though!!
👍

**Comment by RMHogervorst** [comment]
Oooh! Thanks Mara! That is weird but I did copy from a git history. I'll check it out!

**Comment by RMHogervorst** [comment]
I also saw a footnote that didnt render. Never push to prod on Friday is what they say...

**Comment by RMHogervorst** [comment]
I do not see it, Could you screenshot? @batpigandme

**Comment by batpigandme** [comment]
Could it possibly be only on mobile? I'm on my phone, so I can't upload directly, but here's a screenshot I uploaded to imgur https://imgur.com/a/WumHw

**Comment by RMHogervorst** [comment]
Weird! I don't see it on my mobile (android, firefox) or firefox browser . I'll go check it out in other browsers. So it seems to be on the top of the page

**Comment by RMHogervorst** [comment]
check, I see it in chrome!

**Comment by RMHogervorst** [comment]
---- you would not believe how much work this was .... fixed  in 735bc4e9ee2f2d44cbf1c0e8fc588812b860d752

**Comment by batpigandme** [comment]
@RMHogervorst I believe it 100%! Git's gonna git…
